% This function generates the generator of the computation of the directions for each layer
% INPUTS
% Layer of the Interface
% Number of layers of the network
function [] = LastLayerInterface(layer, layers_cnn, padding, padding_conv)
name = sprintf('CNN_Network/CNN/Interfaz_ET%d.vhd', layer);
fid = fopen(name, 'wt');
fprintf(fid, '--------------------INTERFACE LAYER %d----------------------\n', layer );
fprintf(fid, '--This module indicates the position of the filters to calculate the data we need in the input matrix\n');
fprintf(fid, '--INPUTS\n');
fprintf(fid, '--p_rowx, p_colx : signals indicating the amount of padding that affects each of the convolutional filter architecture\n');
fprintf(fid, '--padding_col, padding_row : signals indicating whether the column/row position will be miscalculated due to padding\n');
fprintf(fid, '--data_in : signal indicating the need to compute a new data in this layer\n');
fprintf(fid, '--OUTPUTS\n');
fprintf(fid, '--poolx_col : signal indicating the position of the columns of the filter pool of the current layerst\n');
fprintf(fid, '--poolx_row : signal indicating the position of the rows of the filter pool of the current layers\n');
fprintf(fid, '--convx_col : signal indicating the position of the columns of the convolution filter of the current layer\n');
fprintf(fid, '--convx_row : signal indicating the position of the rows of the convolution filter of the current layer\n');
fprintf(fid, '--zero,: signal that is kept at 1 or zero depending if the data to process is in padding zone or not, it is passed to a multiplexer at the input of the par2ser converter.\n');
fprintf(fid, '--dato_out : signal indicating if a new data is needed, it is passed to the generator of the previous layer.\n');
fprintf(fid, '--data_zero : signals to indicate that the data to be processed is a zero from the padding zone\n');
fprintf(fid,'\n');
fprintf(fid,'library IEEE;\n');
fprintf(fid,'use IEEE.STD_LOGIC_1164.ALL;\n');
fprintf(fid, 'use work.tfg_irene_package.ALL;\n');
fprintf(fid,'use IEEE.NUMERIC_STD.ALL;\n');
fprintf(fid,'\n');
fprintf(fid,'entity INTERFAZ_ET%d is\n', layer);
fprintf(fid, 'Port (clk : in STD_LOGIC;\n');
fprintf(fid, '      rst : in STD_LOGIC;\n');
fprintf(fid, '      rst_red : in std_logic;\n');
fprintf(fid, '      data_in : in std_logic;\n');
fprintf(fid, '      zero : out std_logic;\n');
fprintf(fid, '      data_zero : out std_logic;\n');
fprintf(fid, '      data_out : out std_logic;\n');
fprintf(fid, '      padding_col%d : out std_logic;\n',layer);
fprintf(fid, '      padding_row%d : out std_logic;\n', layer);
fprintf(fid, '      col%d : out unsigned(log2c(column_size%d + 2*(conv%d_padding)) - 1 downto 0);\n', layer, layer, layer);
fprintf(fid, '      p_row%d: out unsigned( log2c(conv%d_padding) downto 0); \n',layer,layer);
fprintf(fid, '      p_col%d : out unsigned( log2c(conv%d_padding) downto 0);  \n',layer,layer);
fprintf(fid, '      conv%d_col : out unsigned(log2c(conv%d_column) - 1 downto 0);\n', layer, layer);
fprintf(fid, '      conv%d_fila : out  unsigned(log2c(conv%d_row) - 1 downto 0);\n', layer, layer);
fprintf(fid, '      pool%d_col : out unsigned(log2c(pool%d_column) - 1 downto 0);\n', layers_cnn, layers_cnn);
fprintf(fid, '      pool%d_fila : out  unsigned(log2c(pool%d_row) - 1 downto 0));\n', layers_cnn, layers_cnn);
fprintf(fid, 'end Interfaz_ET%d;\n', layer);
fprintf(fid,'architecture Behavioral of Interfaz_ET%d is\n', layer);
fprintf(fid,'type state_type is (idle , s_wait, s0, s1,s2);\n');
fprintf(fid,'signal state_reg, state_next : state_type;\n');
if(padding_conv(layers_cnn - 1) == 0)
    fprintf(fid,'signal p_col_aux : unsigned(log2c(column_size%d) - 1 downto 0);\n',layer);
    fprintf(fid,'signal p_row_aux: unsigned(log2c(row_size%d) - 1 downto 0);\n', layer);
else
    fprintf(fid,'signal p_col_aux : unsigned(log2c(column_size%d) downto 0);\n',layer);
    fprintf(fid,'signal p_row_aux: unsigned(log2c(row_size%d) downto 0);\n', layer);
end
fprintf(fid,'signal p_row_reg, p_row_next : unsigned(log2c(conv%d_padding) downto 0);\n', layer);
fprintf(fid,'signal p_col_reg, p_col_next : unsigned(log2c(conv%d_padding) downto 0);\n', layer);
fprintf(fid,'signal col_reg, col_next : unsigned(log2c(column_size%d + 2*(conv%d_padding)) - 1 downto 0) := (others => ''0'');\n', layer, layer);
fprintf(fid,'signal row_reg, row_next :  unsigned(log2c(row_size%d + 2*(conv%d_padding)) - 1 downto 0) := (others => ''0'');\n', layer, layer);
fprintf(fid,'signal c_col_reg, c_col_next, c_row_reg, c_row_next, flag_reg, flag_next : std_logic := ''0'';\n');
fprintf(fid,'\n');
fprintf(fid,'--Layer %d\n', layer);
fprintf(fid,'signal conv%d_col_reg, conv%d_col_next : unsigned(log2c(conv%d_column) - 1 downto 0) := (others => ''0'');\n', layer , layer, layer);
fprintf(fid,'signal conv%d_row_reg, conv%d_row_next : unsigned(log2c(conv%d_row) - 1 downto 0) := (others => ''0'');\n', layer, layer, layer);
fprintf(fid,'-- Layer %d\n', layers_cnn);
fprintf(fid,'signal pool%d_col_reg, pool%d_col_next : unsigned(log2c(pool%d_column) - 1 downto 0) := (others => ''0'');\n', layers_cnn, layers_cnn,layers_cnn);
fprintf(fid,'signal pool%d_row_reg, pool%d_row_next : unsigned(log2c(pool%d_row) - 1 downto 0) := (others => ''0'');\n', layers_cnn, layers_cnn,layers_cnn);
fprintf(fid,'\n');
fprintf(fid,'--Registers\n');
fprintf(fid,'signal first_reg, first_next, zero_reg, zero_next, data_zero_reg, data_zero_next, data_out_reg, data_out_next : std_logic;\n');
fprintf(fid,'\n');
fprintf(fid,'begin\n');
fprintf(fid,'process(clk) \n');
fprintf(fid,'begin \n');
fprintf(fid,'if (clk''event and clk = ''1'') then \n');
fprintf(fid,'\t if (rst = ''0'') then \n');
fprintf(fid,'\t \t state_reg <= idle;\n');
fprintf(fid,'\t else\n');
fprintf(fid,'\t\t state_reg <= state_next; \n');
fprintf(fid,'\t\t col_reg <= col_next; \n');
fprintf(fid,'\t\t row_reg <= row_next; \n');
fprintf(fid,'\t\t pool%d_col_reg <= pool%d_col_next; \n', layers_cnn, layers_cnn);
fprintf(fid,'\t\t pool%d_row_reg <= pool%d_row_next; \n', layers_cnn, layers_cnn);
fprintf(fid,'\t\t conv%d_col_reg <= conv%d_col_next; \n', layer, layer);
fprintf(fid,'\t\t conv%d_row_reg <= conv%d_row_next; \n', layer, layer);
fprintf(fid,'\t\t p_row_reg <= p_row_next; \n');
fprintf(fid,'\t\t p_col_reg <= p_col_next; \n');
fprintf(fid,'\t\t first_reg <= first_next; \n');
fprintf(fid,'\t\t zero_reg <= zero_next; \n');
fprintf(fid,'\t\t c_col_reg <= c_col_next; \n');
fprintf(fid,'\t\t c_row_reg <= c_row_next; \n');
fprintf(fid,'\t\t data_out_reg <= data_out_next;\n');
fprintf(fid,'\t\t data_zero_reg <= data_zero_next; \n');
fprintf(fid,'\t\t flag_reg <= flag_next; \n');
fprintf(fid,'\t end if; \n');
fprintf(fid,'end if; \n');
fprintf(fid,'end process; \n');
fprintf(fid, ' process (rst_red, data_out_reg, data_zero_reg,flag_reg, c_col_reg, c_row_reg, p_row_aux, p_col_aux, p_row_reg, p_col_reg, conv%d_col_next, conv%d_row_next ,conv%d_col_reg, conv%d_row_reg, pool%d_col_next,pool%d_col_reg, pool%d_row_reg, pool%d_row_next,  zero_reg, first_reg, state_reg , row_reg, col_reg, data_in, col_next, row_next, p_row_next, p_col_next)\n', layer, layer, layer, layer, layer + 1, layer + 1, layer +1, layer + 1);
fprintf(fid,'\n');
fprintf(fid,'begin \n');
fprintf(fid,'\t state_next <= state_reg;\n');
fprintf(fid,'\t col_next <= col_reg;\n');
fprintf(fid,'\t row_next <= row_reg;\n');
fprintf(fid,'\t p_col_next <= p_col_reg;\n');
fprintf(fid,'\t p_row_next <= p_row_reg;\n');
fprintf(fid,'\t conv%d_col_next <= conv%d_col_reg;\n', layer, layer );
fprintf(fid,'\t conv%d_row_next <= conv%d_row_reg;\n', layer, layer);
fprintf(fid,'\t pool%d_col_next <= pool%d_col_reg;\n', layers_cnn, layers_cnn);
fprintf(fid,'\t pool%d_row_next <= pool%d_row_reg;\n', layers_cnn, layers_cnn);
fprintf(fid,'\t first_next <= first_reg;\n');
fprintf(fid,'\t zero_next <= zero_reg;\n');
fprintf(fid,'\t c_col_next <= c_col_reg;\n');
fprintf(fid,'\t c_row_next <= c_row_reg;\n');
fprintf(fid,'\t p_row_aux <= (others => ''0'');\n');
fprintf(fid,'\t p_col_aux <= (others => ''0'');\n');
fprintf(fid,'\t flag_next <= flag_reg;\n');
fprintf(fid,'\t data_zero_next <= ''0'';\n');
fprintf(fid,'\t data_out_next <= ''0'';\n');
fprintf(fid,'\n');
fprintf(fid,' case state_reg is \n');
fprintf(fid,'\t when idle =>  \n');
fprintf(fid, 'data_out_next <= ''0'';\n');
fprintf(fid, 'data_zero_next <= ''0'';\n');
fprintf(fid, 'col_next <= (others => ''0'');\n');
fprintf(fid, 'row_next <= (others => ''0'');\n');
fprintf(fid, 'p_row_aux <= (others => ''0'');\n');
fprintf(fid, 'p_col_aux <= (others => ''0'');\n');
fprintf(fid, 'conv%d_col_next <= (others => ''0'');\n', layer);
fprintf(fid, 'conv%d_row_next <= (others => ''0'');\n', layer);
fprintf(fid, 'pool%d_col_next <= (others => ''0'');\n', layers_cnn);
fprintf(fid, 'pool%d_row_next <= (others => ''0'');\n', layers_cnn);
fprintf(fid, 'first_next <= ''1'';\n');
fprintf(fid, 'state_next <= s_wait;\n');
fprintf(fid, 'p_row_next <= (others => ''0'');\n');
fprintf(fid, 'p_col_next <= (others => ''0'');\n');
fprintf(fid, 'zero_next <= ''0'';\n');
fprintf(fid, 'c_col_next <= ''0'';\n');
fprintf(fid, 'c_row_next <= ''0'';\n');
fprintf(fid, 'flag_next <= ''0'';\n');
fprintf(fid, 'when s_wait =>\n');
if(padding == 1)
    fprintf(fid, '\t-- Calculation of padding columns and rows in the filter window being calculated\n');
    fprintf(fid, '\t-- Columns\n');
    fprintf(fid, '\tif(flag_reg = ''1'') then\n');
    fprintf(fid, '\t\tif(conv%d_padding >= col_reg and conv%d_col_reg /= 0) then\n', layer, layer);
    fprintf(fid, '\t\t\tp_col_next <= conv%d_col_reg(log2c(conv%d_padding) downto 0 );\n', layer, layer);
    fprintf(fid, '\t\telsif(col_reg + (conv%d_column - 1) >= padding_columns%d) then\n', layer, layer);
    fprintf(fid, '\t\t\tp_col_aux <= (col_reg + conv%d_column) - padding_columns%d;\n', layer, layer);
    fprintf(fid, '\t\t\tp_col_next <= p_col_aux(log2c(conv%d_padding) downto 0);\n', layer);
    fprintf(fid, '\t\telse\n');
    fprintf(fid, '\t\t\tp_col_next <= (others => ''0'');\n');
    fprintf(fid, '\t\tend if;\n');
    fprintf(fid, '\t-- Rows\n');
    fprintf(fid, '\tif(conv%d_padding >= row_reg and conv%d_row_reg /= 0) then\n', layer, layer);
    fprintf(fid, '\t\tp_row_next <= conv%d_row_reg(log2c(conv%d_padding) downto 0 );\n', layer, layer);
    fprintf(fid, '\telsif(row_reg + (conv%d_row - 1) >= padding_rows%d) then\n', layer, layer);
    fprintf(fid, '\t\tp_row_aux <= (row_reg + conv%d_row) - padding_rows%d;\n', layer, layer);
    fprintf(fid, '\t\tp_row_next <= p_row_aux(log2c(conv%d_padding) downto 0);\n', layer);
    fprintf(fid, '\telse\n');
    fprintf(fid, '\t\tp_row_next <= (others => ''0'');\n');
    fprintf(fid, '\tend if;\n');
    fprintf(fid, 'end if;\n');
else
    fprintf(fid, '\t\tp_row_next <= (others => ''0'');\n');
    fprintf(fid, '\t\t\tp_col_next <= (others => ''0'');\n');
end
fprintf(fid, 'data_out_next <= ''0'';\n');
fprintf(fid, 'data_zero_next <= ''0'';\n');
fprintf(fid, 'c_col_next <= ''0'';\n');
fprintf(fid, 'c_row_next <= ''0'';\n');
fprintf(fid, 'if(data_in = ''1'') then\n');
fprintf(fid, '\tstate_next <= s0;\n');
fprintf(fid, '\tflag_next <= ''0'';\n');
fprintf(fid, 'end if;\n');
fprintf(fid, 'if(rst_red = ''1'') then\n');
fprintf(fid, '\tstate_next <= idle;\n');
fprintf(fid, 'end if;\n');
fprintf(fid,'when s0 => \n');
fprintf(fid,'if(first_reg = ''1'') then\n');
if(padding == 1)
    fprintf(fid,'   first_next <= ''0'';\n');
    fprintf(fid,'   zero_next <= ''1'';\n');
    fprintf(fid,'   data_out_next <= ''0'';\n');
    fprintf(fid,'   data_zero_next <= ''1'';\n');
else
    fprintf(fid,'   first_next <= ''0'';\n');
    fprintf(fid,'   zero_next <= ''0'';\n');
    fprintf(fid,'   data_out_next <= ''1'';\n');
    fprintf(fid,'   data_zero_next <= ''0'';\n');
end
fprintf(fid,'else\n');
fprintf(fid,'  if (conv%d_col_reg /= conv%d_column - 1) then   --If the filter sweep has not finished running through the colums, we add one to the columns.\n', layer, layer);
fprintf(fid,'     col_next <= col_reg + loop_columns%d_1;\n', layer);
fprintf(fid,'     conv%d_col_next <= conv%d_col_reg + 1;\n', layer, layer);
fprintf(fid,'  else\n');
fprintf(fid,'     conv%d_col_next <= (others => ''0'');\n', layer);
fprintf(fid,'     if (conv%d_row_reg /= (conv%d_row - 1)) then      --If the filter sweep  has not finished running trhough the rows, we add one to the row and return the original value to the columns.\n', layer, layer);
fprintf(fid,'        col_next <= col_reg - loop_columns%d_2;\n',layer);
fprintf(fid,'        row_next <= row_reg + loop_rows%d_1;\n',layer);
fprintf(fid,'        conv%d_row_next <= conv%d_row_reg + 1;\n',layer,layer);
fprintf(fid,'     else\n');
fprintf(fid,'        conv%d_row_next <= (others => ''0''); \n', layer);
fprintf(fid,'        if (pool%d_col_reg /= pool%d_column - 1) then\n', layers_cnn, layers_cnn);
fprintf(fid,'           row_next <= row_reg - loop_rows%d_2;\n',layer);
fprintf(fid,'           col_next <= col_reg - loop_columns%d_3;\n',layer);
fprintf(fid,'           pool%d_col_next <= pool%d_col_reg + 1;\n', layers_cnn, layers_cnn);
fprintf(fid,'        else\n');
fprintf(fid,'           pool%d_col_next <= (others => ''0'');\n',layers_cnn);
fprintf(fid,'           if (pool%d_row_reg /= (pool%d_row - 1)) then \n', layer+1, layer+1);
fprintf(fid,'               row_next <= row_reg - loop_rows%d_3;\n', layer);
fprintf(fid,'               col_next <= col_reg - loop_columns%d_4;  \n',layer);
fprintf(fid,'               pool%d_row_next <= pool%d_row_reg + 1; \n', layers_cnn, layers_cnn);
fprintf(fid,'           else\n');
fprintf(fid,'               pool%d_row_next <= (others => ''0'');\n', layers_cnn);
fprintf(fid,'               if(col_reg /= column_limit%d - 1) then\n',layer);
fprintf(fid,'                  row_next <= row_reg - loop_rows%d_4;\n', layer);
fprintf(fid,'                  col_next <= col_reg - loop_columns%d_5;\n', layer);
fprintf(fid,'               else \n');
fprintf(fid,'                  row_next <= row_reg - loop_rows%d_5;\n', layer);
fprintf(fid,'                  col_next <= (others => ''0'');\n');
fprintf(fid,'                  if(row_reg = row_limit%d) then\n',layer);
fprintf(fid,'                     row_next <= (others => ''0'');\n');
fprintf(fid,'                  end if;\n');
fprintf(fid,'               end if;\n');
fprintf(fid,'           end if;\n');
fprintf(fid,'        end if;\n');
fprintf(fid,'     end if;\n');
fprintf(fid,'   end if;\n');
fprintf(fid,'end if;\n');
fprintf(fid,'state_next <= s1;\n');
fprintf(fid,' when s1 =>\n');
if(padding == 1)
    fprintf(fid, 'if( (col_reg >= conv%d_padding) and (col_reg < padding_columns%d )) and ((row_reg  >= conv%d_padding) and (row_reg < padding_rows%d )) then\n', layer, layer, layer,layer);
    fprintf(fid, '\tif( row_reg = conv%d_padding) then\n', layer);
    fprintf(fid, '\t\tif(zero_reg = ''1'') then\n');
    fprintf(fid, '\t\t\tflag_next <= ''1'';\n');
    fprintf(fid, '\t\tend if;\n');
    fprintf(fid, '\t\tc_row_next <= ''1'';\n');
    fprintf(fid, '\tend if;\n');
    fprintf(fid, '\tif(col_reg = conv%d_padding) then\n', layer);
    fprintf(fid, '\t\tif(zero_reg = ''1'' and conv%d_row_reg = 0) then\n', layer);
    fprintf(fid, '\t\t\tflag_next <= ''1'';\n');
    fprintf(fid, '\t\tend if;\n');
    fprintf(fid, '\t\tc_col_next <= ''1'';\n');
    fprintf(fid, '\tend if;\n');
    fprintf(fid, '\tif(conv%d_row_reg = 0 and conv%d_col_reg = 0) then\n', layer, layer);
    fprintf(fid, '\t\tflag_next <= ''1'';\n');
    fprintf(fid, '\tend if;\n');
    fprintf(fid, '\tdata_out_next <= ''1'';\n');
    fprintf(fid, '\tdata_zero_next <= ''0'';\n');
    fprintf(fid, '\tzero_next <= ''0'';\n');
    fprintf(fid, 'else\n');
    fprintf(fid, '\tdata_out_next <= ''0'';\n');
    fprintf(fid, '\tdata_zero_next <= ''1'';\n');
    fprintf(fid, '\tzero_next <= ''1'';\n');
    fprintf(fid, 'end if;\n');
else
    fprintf(fid, '\tdata_out_next <= ''1'';\n');
    fprintf(fid, '\tdata_zero_next <= ''0'';\n');
    fprintf(fid, '\tzero_next <= ''0'';\n');
end
fprintf(fid, 'state_next <= s2;\n');
fprintf(fid, 'when s2 =>\n');
fprintf(fid, '\tdata_zero_next <= ''0'';\n');
fprintf(fid, '\tstate_next <= s_wait;\n');
fprintf(fid, 'end case;\n');
fprintf(fid, 'end process;\n');
fprintf(fid, '-- Output signals\n');
fprintf(fid, 'col%d <= col_reg;\n', layer);
fprintf(fid, 'conv%d_col <= conv%d_col_reg;\n', layer, layer);
fprintf(fid, 'conv%d_fila <= conv%d_row_reg;\n', layer, layer);
fprintf(fid, 'pool%d_col <= pool%d_col_reg;\n', layers_cnn, layers_cnn);
fprintf(fid, 'pool%d_fila <= pool%d_row_reg;\n', layers_cnn, layers_cnn);
fprintf(fid, 'zero <= zero_reg;\n');
fprintf(fid, 'p_col%d <= p_col_reg;\n', layer);
fprintf(fid, 'p_row%d <= p_row_reg;\n', layer);
fprintf(fid, 'padding_col%d <= c_col_reg;\n', layer);
fprintf(fid, 'padding_row%d <= c_row_reg;\n', layer);
fprintf(fid, 'data_out <= data_out_reg;\n');
fprintf(fid, 'data_zero <= data_zero_reg;\n');
fprintf(fid, 'end Behavioral;\n');
fclose(fid);
end

